kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "device-events.fullname" . }}
  labels:
    {{- include "device-events.labels" . | nindent 4 }}
data:
  device-events.yaml: |
{{ tpl (toYaml .Values.config) . | indent 4 }}
