resources:
  requests:
    cpu: 10m
    memory: 65Mi
  limits:
    cpu: 200m
    memory: 128Mi

config:
  logging:
    level: "debug"

dragonfly:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: "1"
      memory: 2Gi
